-- public.book_author определение

-- Drop table

-- DROP TABLE public.book_author;

CREATE TABLE public.book_author (
	author_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	birth_date timestamp(6) NULL,
	first_name varchar(255) NULL,
	identifier varchar(255) NULL,
	second_name varchar(255) NULL,
	third_name varchar(255) NULL,
	CONSTRAINT book_author_identifier_key UNIQUE (identifier),
	CONSTRAINT book_author_pkey PRIMARY KEY (author_id)
);


-- public.book_genre определение

-- Drop table

-- DROP TABLE public.book_genre;

CREATE TABLE public.book_genre (
	genre_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	genre_name varchar(255) NULL,
	CONSTRAINT book_genre_pkey PRIMARY KEY (genre_id)
);


-- public.book_language определение

-- Drop table

-- DROP TABLE public.book_language;

CREATE TABLE public.book_language (
	language_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	language_name varchar(255) NULL,
	CONSTRAINT book_language_pkey PRIMARY KEY (language_id)
);


-- public.book_relation определение

-- Drop table

-- DROP TABLE public.book_relation;

CREATE TABLE public.book_relation (
	relation_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	relation_name varchar(255) NULL,
	CONSTRAINT book_relation_pkey PRIMARY KEY (relation_id)
);


-- public.book_status определение

-- Drop table

-- DROP TABLE public.book_status;

CREATE TABLE public.book_status (
	book_status_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	status_name varchar(255) NULL,
	CONSTRAINT book_status_pkey PRIMARY KEY (book_status_id)
);


-- public.books_arriving определение

-- Drop table

-- DROP TABLE public.books_arriving;

CREATE TABLE public.books_arriving (
	arriving_dttm timestamp(6) NULL,
	arriving_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT books_arriving_pkey PRIMARY KEY (arriving_id)
);


-- public.borrow_status определение

-- Drop table

-- DROP TABLE public.borrow_status;

CREATE TABLE public.borrow_status (
	borrow_status_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	status_name varchar(255) NULL,
	CONSTRAINT borrow_status_pkey PRIMARY KEY (borrow_status_id)
);


-- public.cabinet определение

-- Drop table

-- DROP TABLE public.cabinet;

CREATE TABLE public.cabinet (
	cabinet_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cabinet_number int4 NOT NULL,
	cabinet_name varchar(255) NULL,
	CONSTRAINT cabinet_pkey PRIMARY KEY (cabinet_id)
);


-- public.in_order_book определение

-- Drop table

-- DROP TABLE public.in_order_book;

CREATE TABLE public.in_order_book (
	is_recieved bool NOT NULL,
	book_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	release_date timestamp(6) NULL,
	"comment" varchar(1000) NULL,
	book_author varchar(255) NULL,
	book_name varchar(255) NULL,
	publishing_house varchar(255) NULL,
	CONSTRAINT in_order_book_pkey PRIMARY KEY (book_id)
);


-- public.publishing_house определение

-- Drop table

-- DROP TABLE public.publishing_house;

CREATE TABLE public.publishing_house (
	publishing_house_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	publishing_house_name varchar(255) NULL,
	CONSTRAINT publishing_house_pkey PRIMARY KEY (publishing_house_id)
);


-- public."user" определение

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	"role" int2 NULL,
	birth_date timestamp(6) NULL,
	register_dttm timestamp(6) NULL,
	user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	"password" varchar(255) NULL,
	second_name varchar(255) NULL,
	third_name varchar(255) NULL,
	CONSTRAINT user_email_key UNIQUE (email),
	CONSTRAINT user_pkey PRIMARY KEY (user_id),
	CONSTRAINT user_role_check CHECK (((role >= 0) AND (role <= 5)))
);


-- public.user_role определение

-- Drop table

-- DROP TABLE public.user_role;

CREATE TABLE public.user_role (
	role_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_name varchar(255) NULL,
	CONSTRAINT user_role_pkey PRIMARY KEY (role_id)
);


-- public.book определение

-- Drop table

-- DROP TABLE public.book;

CREATE TABLE public.book (
	book_status int2 NULL,
	language_language_id int4 NULL,
	pages_number int4 NOT NULL,
	add_dttm timestamp(6) NULL,
	book_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	publishing_house_publishing_house_id int8 NULL,
	release_date timestamp(6) NULL,
	description varchar(10000) NULL,
	book_name varchar(255) NULL,
	identifier varchar(255) NULL,
	CONSTRAINT book_book_status_check CHECK (((book_status >= 0) AND (book_status <= 3))),
	CONSTRAINT book_identifier_key UNIQUE (identifier),
	CONSTRAINT book_pkey PRIMARY KEY (book_id),
	CONSTRAINT fk9sue6r15ojait6mqpqbtopj26 FOREIGN KEY (publishing_house_publishing_house_id) REFERENCES public.publishing_house(publishing_house_id) ON DELETE SET NULL,
	CONSTRAINT fksnmbsrop5evsoiy5fgnnuisre FOREIGN KEY (language_language_id) REFERENCES public.book_language(language_id) ON DELETE SET NULL
);


-- public.book_authors определение

-- Drop table

-- DROP TABLE public.book_authors;

CREATE TABLE public.book_authors (
	authors_author_id int8 NOT NULL,
	book_book_id int8 NOT NULL,
	CONSTRAINT fkkihxjrhtgy1t03ttdivy1misg FOREIGN KEY (book_book_id) REFERENCES public.book(book_id) ON DELETE SET NULL,
	CONSTRAINT fkthii9cpr90jk2cf30qqhrpodi FOREIGN KEY (authors_author_id) REFERENCES public.book_author(author_id)
);


-- public.book_genres определение

-- Drop table

-- DROP TABLE public.book_genres;

CREATE TABLE public.book_genres (
	genres_genre_id int4 NOT NULL,
	book_book_id int8 NOT NULL,
	CONSTRAINT fkai44sfnl5ywap4186w6h5tyac FOREIGN KEY (book_book_id) REFERENCES public.book(book_id) ON DELETE SET NULL,
	CONSTRAINT fkm15v5yq7ckv98mhxbhlkpe298 FOREIGN KEY (genres_genre_id) REFERENCES public.book_genre(genre_id)
);


-- public.book_to_book_relation определение

-- Drop table

-- DROP TABLE public.book_to_book_relation;

CREATE TABLE public.book_to_book_relation (
	relation_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	relation_relation_id int4 NULL,
	main_book_book_id int8 NULL,
	related_book_book_id int8 NULL,
	relation_description varchar(255) NULL,
	CONSTRAINT book_to_book_relation_pkey PRIMARY KEY (relation_id),
	CONSTRAINT fkgmnpso59cl1ofp686u9s0x0mj FOREIGN KEY (related_book_book_id) REFERENCES public.book(book_id) ON DELETE SET NULL,
	CONSTRAINT fkkxg9brblfr1gedl1lteal7c3t FOREIGN KEY (main_book_book_id) REFERENCES public.book(book_id) ON DELETE SET NULL,
	CONSTRAINT fkodwoyo8500n6jwp8dcxyfi7fn FOREIGN KEY (relation_relation_id) REFERENCES public.book_relation(relation_id) ON DELETE SET NULL
);


-- public.books_arriving_arrived_books определение

-- Drop table

-- DROP TABLE public.books_arriving_arrived_books;

CREATE TABLE public.books_arriving_arrived_books (
	arrived_books_book_id int8 NOT NULL,
	books_arriving_arriving_id int8 NOT NULL,
	CONSTRAINT fk3vo5488sxwxt7p95xyxepf1w2 FOREIGN KEY (books_arriving_arriving_id) REFERENCES public.books_arriving(arriving_id),
	CONSTRAINT fkjdltv2ej1wvtruw5h4ystues6 FOREIGN KEY (arrived_books_book_id) REFERENCES public.in_order_book(book_id)
);


-- public.books_arriving_orderings определение

-- Drop table

-- DROP TABLE public.books_arriving_orderings;

CREATE TABLE public.books_arriving_orderings (
	books_arriving_arriving_id int8 NOT NULL,
	orderings_book_id int8 NOT NULL,
	CONSTRAINT fkacd23wkj38m0c8p41hh4aado FOREIGN KEY (orderings_book_id) REFERENCES public.in_order_book(book_id),
	CONSTRAINT fkp0k94jmkyti0mjs5c5ogj053w FOREIGN KEY (books_arriving_arriving_id) REFERENCES public.books_arriving(arriving_id) ON DELETE SET NULL
);


-- public.bookshelf определение

-- Drop table

-- DROP TABLE public.bookshelf;

CREATE TABLE public.bookshelf (
	cabinet_cabinet_id int4 NULL,
	shelf_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	shelf_name varchar(255) NULL,
	CONSTRAINT bookshelf_pkey PRIMARY KEY (shelf_id),
	CONSTRAINT fka0hcekyw3gvdpq06qdul0yl9y FOREIGN KEY (cabinet_cabinet_id) REFERENCES public.cabinet(cabinet_id) ON DELETE SET NULL
);


-- public.bookshelf_books определение

-- Drop table

-- DROP TABLE public.bookshelf_books;

CREATE TABLE public.bookshelf_books (
	bookshelf_shelf_id int4 NOT NULL,
	books_book_id int8 NOT NULL,
	CONSTRAINT bookshelf_books_books_book_id_key UNIQUE (books_book_id),
	CONSTRAINT fk2gwli8nv8yhkygfk4k9vkoc5r FOREIGN KEY (bookshelf_shelf_id) REFERENCES public.bookshelf(shelf_id),
	CONSTRAINT fksencsq2y9e9k4mq0vvb431hyq FOREIGN KEY (books_book_id) REFERENCES public.book(book_id)
);


-- public.borrow определение

-- Drop table

-- DROP TABLE public.borrow;

CREATE TABLE public.borrow (
	borrow_status int2 NULL,
	redemption_price_if_loss int4 NULL,
	borrow_dttm timestamp(6) NULL,
	borrow_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	borrowed_book_book_id int8 NULL,
	borrowed_user_user_id int8 NULL,
	expected_reciept_date timestamp(6) NULL,
	expected_return_date timestamp(6) NULL,
	fact_reciept_dttm timestamp(6) NULL,
	fact_return_dttm timestamp(6) NULL,
	paid_dttm timestamp(6) NULL,
	CONSTRAINT borrow_borrow_status_check CHECK (((borrow_status >= 0) AND (borrow_status <= 4))),
	CONSTRAINT borrow_pkey PRIMARY KEY (borrow_id),
	CONSTRAINT fkcrt3r07eir3tnxmtorroljt2b FOREIGN KEY (borrowed_book_book_id) REFERENCES public.book(book_id) ON DELETE SET NULL,
	CONSTRAINT fko6699pip10k6hsldtjbn846uo FOREIGN KEY (borrowed_user_user_id) REFERENCES public."user"(user_id) ON DELETE SET NULL
);


-- public.cabinet_shelves определение

-- Drop table

-- DROP TABLE public.cabinet_shelves;

CREATE TABLE public.cabinet_shelves (
	cabinet_cabinet_id int4 NOT NULL,
	shelves_shelf_id int4 NOT NULL,
	CONSTRAINT cabinet_shelves_shelves_shelf_id_key UNIQUE (shelves_shelf_id),
	CONSTRAINT fkjcoof78lp3shpu2su2qmsenl9 FOREIGN KEY (cabinet_cabinet_id) REFERENCES public.cabinet(cabinet_id),
	CONSTRAINT fkq2khfncin6wq582w4gykd7bqo FOREIGN KEY (shelves_shelf_id) REFERENCES public.bookshelf(shelf_id)
);


-- public.entry_code определение

-- Drop table

-- DROP TABLE public.entry_code;

CREATE TABLE public.entry_code (
	code_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	expire_date_time timestamp(6) NULL,
	user_user_id int8 NULL,
	code varchar(255) NULL,
	CONSTRAINT entry_code_pkey PRIMARY KEY (code_id),
	CONSTRAINT entry_code_user_user_id_key UNIQUE (user_user_id),
	CONSTRAINT fkornnaqf5kmqy4qgg6iw2x43rc FOREIGN KEY (user_user_id) REFERENCES public."user"(user_id) ON DELETE CASCADE
);


-- public.notification определение

-- Drop table

-- DROP TABLE public.notification;

CREATE TABLE public.notification (
	is_checked bool NOT NULL,
	notification_dttm timestamp(6) NULL,
	notification_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_user_id int8 NULL,
	"text" varchar(255) NULL,
	title varchar(255) NULL,
	CONSTRAINT notification_pkey PRIMARY KEY (notification_id),
	CONSTRAINT fknosulxdrf81d3yyo9w2vq5shi FOREIGN KEY (user_user_id) REFERENCES public."user"(user_id)
);


-- public.ordering_books определение

-- Drop table

-- DROP TABLE public.ordering_books;

CREATE TABLE public.ordering_books (
	is_active bool NOT NULL,
	expected_arrival_date timestamp(6) NULL,
	ordered_administrator_user_id int8 NULL,
	ordering_dttm timestamp(6) NULL,
	ordering_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"comment" varchar(255) NULL,
	CONSTRAINT ordering_books_pkey PRIMARY KEY (ordering_id),
	CONSTRAINT fki26d365qgpl45rygl9fufr7lw FOREIGN KEY (ordered_administrator_user_id) REFERENCES public."user"(user_id) ON DELETE SET NULL
);


-- public.ordering_books_ordered_books определение

-- Drop table

-- DROP TABLE public.ordering_books_ordered_books;

CREATE TABLE public.ordering_books_ordered_books (
	ordered_books_book_id int8 NOT NULL,
	ordering_books_ordering_id int8 NOT NULL,
	CONSTRAINT fkmvh6xe4pcnu1ucdw6lj5idw7v FOREIGN KEY (ordered_books_book_id) REFERENCES public.in_order_book(book_id),
	CONSTRAINT fkq1s4qyuhbrevmt4eskkcqg2jp FOREIGN KEY (ordering_books_ordering_id) REFERENCES public.ordering_books(ordering_id)
);


-- public.request_books определение

-- Drop table

-- DROP TABLE public.request_books;

CREATE TABLE public.request_books (
	is_active bool NOT NULL,
	request_dttm timestamp(6) NULL,
	request_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	requested_user_user_id int8 NULL,
	"comment" varchar(255) NULL,
	CONSTRAINT request_books_pkey PRIMARY KEY (request_id),
	CONSTRAINT fk76c28acshhs3am7rg9c4fc0wq FOREIGN KEY (requested_user_user_id) REFERENCES public."user"(user_id) ON DELETE SET NULL
);


-- public.request_books_ordered_books определение

-- Drop table

-- DROP TABLE public.request_books_ordered_books;

CREATE TABLE public.request_books_ordered_books (
	ordered_books_book_id int8 NOT NULL,
	request_books_request_id int8 NOT NULL,
	CONSTRAINT fkarge747pn59toqy7yym53xpff FOREIGN KEY (ordered_books_book_id) REFERENCES public.in_order_book(book_id),
	CONSTRAINT fktreefacqiwt1x9sg3x8o1lxel FOREIGN KEY (request_books_request_id) REFERENCES public.request_books(request_id)
);


-- public.book_relation_book_to_book_relations определение

-- Drop table

-- DROP TABLE public.book_relation_book_to_book_relations;

CREATE TABLE public.book_relation_book_to_book_relations (
	book_relation_relation_id int4 NOT NULL,
	book_to_book_relations_relation_id int4 NOT NULL,
	CONSTRAINT book_relation_book_to_book_re_book_to_book_relations_relati_key UNIQUE (book_to_book_relations_relation_id),
	CONSTRAINT fk3kpfvd84pxte4edaruqbchuxv FOREIGN KEY (book_relation_relation_id) REFERENCES public.book_relation(relation_id),
	CONSTRAINT fk5wyn87d9nw0j8x98toosovdua FOREIGN KEY (book_to_book_relations_relation_id) REFERENCES public.book_to_book_relation(relation_id)
);